name: 'Parse issue'
description: 'Parse issue title and body and get the metadata of new article.'
author: 'Sho Kitamura'

inputs:
  issue_title:
    description: 'Issue title'
    required: true
  issue_body:
    description: 'Issue body'
    required: true

outputs:
  title:
    description: 'Title of the article'
  date:
    description: 'Date of the article'
  author:
    description: 'Author of the article'
  body:
    description: 'Body of the article'

runs:
  using: node20
  main: dist/index.js
