name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    env:
      BODY: null

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          {
            echo 'BODY<<EOF'
            echo '<!--'
            echo 'author=My name'
            echo 'date=2021-10-01'
            echo '-->'
            echo 'Test Body'
            echo 'EOF'
          } >> "$GITHUB_ENV"

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          issue_title: 'Test Issue'
          issue_body: ${{ env.BODY }}

      - name: Print Output
        id: output
        run: |
          echo "${{ steps.test-action.outputs.title }}"
          echo "${{ steps.test-action.outputs.date }}"
          echo "${{ steps.test-action.outputs.author }}"
          echo "${{ steps.test-action.outputs.body }}"
